services:
  - type: web
    name: drive-analyzer-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: OAUTHLIB_INSECURE_TRANSPORT
        value: 1
